name: Upload BOM

on:
    push:
        branches: [main]

jobs:
    upload-bom:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "latest"
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - name: Validate Wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  dependency-graph: generate-and-submit
            - name: Gradle Build
              run: ./gradlew build
            - name: Upload BOM
              uses: ./action
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  apiKey: ${{ secrets.VA_API_KEY }}
                  server: https://va-web-am2gwvqqva-ew.a.run.app
                  project: vulnaware-278874
